apiVersion: v1
kind: Service
metadata:
  name: ws-svc
  namespace: workshop
spec:
  ports:
  - port: 80   # service port
    targetPort: 8080  # container port
    protocol: TCP
  type: ClusterIP
  selector:
    app: websocket-app




